version: "3.1"

services:
  php:
    build: .
    ports:
      - "10005:80"
    volumes:
      - ./mysql_info.php:/var/www/config/mysql_info.php
    depends_on:
      - db
    environment:
      - FLAG=${FLAG}

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
